services:
  NITSAN\NsFaq\RecordList\DatabaseRecordList:
    shared: false
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Imaging\IconFactory'
      - '@TYPO3\CMS\Backend\Routing\UriBuilder'
      - '@TYPO3\CMS\Backend\Configuration\TranslationConfigurationProvider'
      - '@Psr\EventDispatcher\EventDispatcherInterface'