services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsFaq\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  NITSAN\NsFaq\Controller\FaqController:
    public: true
    arguments:
      $faqRepository: '@NITSAN\NsFaq\Domain\Repository\FaqRepository'
